name = "ideon"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[observability]
enabled = true


